---
########################################
# Launch services on swarm
########################################
- hosts: haproxys
  remote_user: "{{ admin_user }}"
  tasks:
    - name: Tag haproxy in docker swarm.
      shell: "docker node update --label-add haproxy=true {{ ansible_hostname }}"

- hosts: managers[0]
  remote_user: "{{ admin_user }}"
  vars:
    certs_list:
      - ca.pem
      - cert.pem
      - key.pem
  tasks:
    - name: Copy docker to remote.
      copy:
        src: ../../docker
        dest: "/home/{{ ansible_user }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644
        force: yes

    - name: Copy certificates into folders of docker images that will use tcp to connect to host daemon.
      copy:
        src: "{{ docker_tls_certs_path }}/{{ item.1 }}"
        dest: "{{ item.0 }}/certs/{{ item.1 }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644
        remote_src: yes
      with_nested:
        - ["/home/{{ ansible_user }}/docker/managers/jenkins-master", "/home/{{ ansible_user }}/docker/managers/jenkins-node-slave"]
        - "{{ certs_list }}"

    - name: Start swarm services.
      block:
        - name: Check if the registry service is already started
          shell: "docker service ls | grep registry"
          ignore_errors: yes
          changed_when: false
          register: registry_started

        - name: Start the registry as a service
          command: |
            docker service create \
              --name registry \
              -p 5000:5000  \
              -p 5000:5000/udp  \
              registry:2
          when: registry_started.stdout == ""

        - name: Build docker stack.
          shell: docker-compose -f docker-compose.swarm.yml build
          args:
              chdir: "/home/{{ ansible_user }}/docker/managers"

        - name: Push docker stack.
          shell: docker-compose -f docker-compose.swarm.yml push
          args:
              chdir: "/home/{{ ansible_user }}/docker/managers"

        - name: Deploy stack.
          shell: docker stack deploy -c docker-compose.swarm.yml docker_services
          args:
              chdir: "/home/{{ ansible_user }}/docker/managers"
